version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - whitespace
  disable-all: true

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G104  # Audit errors not checked
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'

run:
  tests: true
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - gosec
        - govet
    - path: main.go
      text: "G104:"  # Excluding error checking in main for brevity
  max-same-issues: 0