# --- build stage
FROM golang:1.22.0 AS builder

WORKDIR /builder/app
COPY go/src/app/ .
COPY go.mod .

RUN go get    -d -v .           &&\
    go build  -v -o /go/bin/app .


# --- Testing image
FROM ubuntu:latest
LABEL Name=kapparmor
LABEL Author="Affinito Alessandro"

WORKDIR /app

RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get install --no-install-recommends --yes \
        apparmor apparmor-utils \
        tini &&\
    rm -rf /var/lib/apt/lists/* &&\
    mkdir --parent --verbose /etc/apparmor.d/custom 

COPY --from=builder /go/bin/app /app/
COPY ./charts/kapparmor/profiles /app/profiles/

ARG PROFILES_DIR
ARG POLL_TIME

ENV PROFILES_DIR=$PROFILES_DIR
ENV POLL_TIME=$POLL_TIME

USER root
ENTRYPOINT ["/usr/bin/tini", "./app"]